import {
  Heart,
  GraduationCap,
  Shield,
  Zap,
  Wifi,
  Droplets,
  TreePine,
  Factory,
  Users,
  Globe,
  Gavel,
  Home,
  Banknote,
  Cpu,
  Car,
} from "lucide-react"

export const ministries = [
  {
    id: "health",
    name: "Federal Ministry of Health",
    description: "Healthcare services, medical certifications, and public health programs",
    icon: Heart,
    services: [
      {
        id: "medical_certificate",
        name: "Medical Certificate",
        description: "Official medical certificate for various purposes",
        duration: 30,
        fee: 5000,
        requirements: ["Valid ID", "Medical examination", "Passport photograph"],
      },
      {
        id: "health_insurance",
        name: "Health Insurance Registration",
        description: "Register for National Health Insurance Scheme",
        duration: 45,
        fee: 0,
        requirements: ["Valid ID", "Proof of residence", "Employment letter"],
      },
      {
        id: "vaccination_certificate",
        name: "Vaccination Certificate",
        description: "International vaccination certificate",
        duration: 20,
        fee: 3000,
        requirements: ["Valid ID", "Vaccination records", "Passport photograph"],
      },
      {
        id: "drug_registration",
        name: "Drug Registration",
        description: "Register pharmaceutical products",
        duration: 60,
        fee: 50000,
        requirements: ["Company registration", "Product specifications", "Laboratory reports"],
      },
    ],
  },
  {
    id: "education",
    name: "Federal Ministry of Education",
    description: "Educational services, certificate verification, and academic programs",
    icon: GraduationCap,
    services: [
      {
        id: "certificate_verification",
        name: "Certificate Verification",
        description: "Verify educational certificates and transcripts",
        duration: 30,
        fee: 2000,
        requirements: ["Original certificate", "Valid ID", "Application form"],
      },
      {
        id: "scholarship_application",
        name: "Scholarship Application",
        description: "Apply for federal government scholarships",
        duration: 45,
        fee: 0,
        requirements: ["Academic transcripts", "Admission letter", "Financial documents"],
      },
      {
        id: "school_registration",
        name: "School Registration",
        description: "Register new educational institutions",
        duration: 90,
        fee: 100000,
        requirements: ["Land documents", "Building approval", "Curriculum proposal"],
      },
    ],
  },
  {
    id: "interior",
    name: "Federal Ministry of Interior",
    description: "Immigration, passport services, and internal security matters",
    icon: Shield,
    services: [
      {
        id: "passport_application",
        name: "Passport Application",
        description: "Apply for new Nigerian passport",
        duration: 60,
        fee: 25000,
        requirements: ["Birth certificate", "Valid ID", "Passport photographs", "Guarantor form"],
      },
      {
        id: "passport_renewal",
        name: "Passport Renewal",
        description: "Renew expired Nigerian passport",
        duration: 45,
        fee: 25000,
        requirements: ["Old passport", "Valid ID", "Passport photographs"],
      },
      {
        id: "visa_application",
        name: "Visa Application",
        description: "Apply for entry visa to Nigeria",
        duration: 30,
        fee: 15000,
        requirements: ["Valid passport", "Invitation letter", "Passport photographs"],
      },
      {
        id: "residence_permit",
        name: "Residence Permit",
        description: "Apply for residence permit in Nigeria",
        duration: 90,
        fee: 50000,
        requirements: ["Valid passport", "Employment letter", "Tax clearance"],
      },
    ],
  },
  {
    id: "justice",
    name: "Federal Ministry of Justice",
    description: "Legal services, court matters, and justice administration",
    icon: Gavel,
    services: [
      {
        id: "legal_aid",
        name: "Legal Aid Application",
        description: "Apply for free legal representation",
        duration: 30,
        fee: 0,
        requirements: ["Valid ID", "Income statement", "Case documents"],
      },
      {
        id: "notarization",
        name: "Document Notarization",
        description: "Notarize legal documents",
        duration: 15,
        fee: 1000,
        requirements: ["Original document", "Valid ID"],
      },
      {
        id: "company_registration",
        name: "Company Registration",
        description: "Register new business entity",
        duration: 60,
        fee: 10000,
        requirements: ["Memorandum of association", "Articles of association", "Directors details"],
      },
    ],
  },
  {
    id: "finance",
    name: "Federal Ministry of Finance",
    description: "Tax services, revenue collection, and financial matters",
    icon: Banknote,
    services: [
      {
        id: "tax_clearance",
        name: "Tax Clearance Certificate",
        description: "Obtain tax clearance certificate",
        duration: 30,
        fee: 2000,
        requirements: ["Tax returns", "Valid ID", "Bank statements"],
      },
      {
        id: "tin_registration",
        name: "TIN Registration",
        description: "Register for Tax Identification Number",
        duration: 20,
        fee: 0,
        requirements: ["Valid ID", "Proof of address", "Passport photograph"],
      },
      {
        id: "customs_clearance",
        name: "Customs Clearance",
        description: "Clear goods through customs",
        duration: 45,
        fee: 5000,
        requirements: ["Import documents", "Invoice", "Packing list"],
      },
    ],
  },
  {
    id: "works",
    name: "Federal Ministry of Works and Housing",
    description: "Infrastructure development, housing programs, and construction permits",
    icon: Home,
    services: [
      {
        id: "building_permit",
        name: "Building Permit",
        description: "Obtain permit for construction projects",
        duration: 60,
        fee: 20000,
        requirements: ["Architectural drawings", "Land documents", "Environmental impact assessment"],
      },
      {
        id: "housing_application",
        name: "Federal Housing Application",
        description: "Apply for federal housing scheme",
        duration: 90,
        fee: 10000,
        requirements: ["Employment letter", "Income statement", "Bank statements"],
      },
      {
        id: "road_permit",
        name: "Road Construction Permit",
        description: "Permit for road construction and maintenance",
        duration: 45,
        fee: 50000,
        requirements: ["Engineering drawings", "Environmental clearance", "Company registration"],
      },
    ],
  },
  {
    id: "power",
    name: "Federal Ministry of Power",
    description: "Electricity services, power generation, and energy regulation",
    icon: Zap,
    services: [
      {
        id: "electricity_connection",
        name: "Electricity Connection",
        description: "Apply for new electricity connection",
        duration: 30,
        fee: 15000,
        requirements: ["Property documents", "Valid ID", "Electrical installation certificate"],
      },
      {
        id: "power_generation_license",
        name: "Power Generation License",
        description: "License for power generation facilities",
        duration: 120,
        fee: 500000,
        requirements: ["Technical specifications", "Environmental impact assessment", "Financial capacity proof"],
      },
      {
        id: "meter_installation",
        name: "Prepaid Meter Installation",
        description: "Install prepaid electricity meter",
        duration: 20,
        fee: 8000,
        requirements: ["Property documents", "Valid ID", "Electricity bill"],
      },
    ],
  },
  {
    id: "transport",
    name: "Federal Ministry of Transportation",
    description: "Transport services, vehicle registration, and aviation matters",
    icon: Car,
    services: [
      {
        id: "drivers_license",
        name: "Drivers License",
        description: "Apply for or renew drivers license",
        duration: 45,
        fee: 6500,
        requirements: ["Valid ID", "Medical certificate", "Passport photographs", "Driving test certificate"],
      },
      {
        id: "vehicle_registration",
        name: "Vehicle Registration",
        description: "Register new or used vehicle",
        duration: 30,
        fee: 12000,
        requirements: ["Purchase receipt", "Insurance certificate", "Valid ID", "Vehicle inspection certificate"],
      },
      {
        id: "aviation_license",
        name: "Aviation License",
        description: "Pilot or aviation personnel license",
        duration: 90,
        fee: 100000,
        requirements: ["Medical certificate", "Training certificates", "Flight hours log"],
      },
      {
        id: "maritime_license",
        name: "Maritime License",
        description: "Marine vessel or personnel license",
        duration: 60,
        fee: 75000,
        requirements: ["Training certificates", "Medical certificate", "Sea time records"],
      },
    ],
  },
  {
    id: "communications",
    name: "Federal Ministry of Communications and Digital Economy",
    description: "ICT services, telecommunications, and digital innovation",
    icon: Wifi,
    services: [
      {
        id: "telecom_license",
        name: "Telecommunications License",
        description: "License for telecommunications services",
        duration: 90,
        fee: 1000000,
        requirements: ["Technical proposal", "Financial capacity proof", "Company registration"],
      },
      {
        id: "domain_registration",
        name: "Domain Name Registration",
        description: "Register .ng domain name",
        duration: 15,
        fee: 5000,
        requirements: ["Valid ID", "Company registration (for organizations)"],
      },
      {
        id: "digital_certificate",
        name: "Digital Certificate",
        description: "Digital signature certificate",
        duration: 30,
        fee: 10000,
        requirements: ["Valid ID", "Biometric data", "Application form"],
      },
    ],
  },
  {
    id: "water",
    name: "Federal Ministry of Water Resources",
    description: "Water supply, irrigation, and water resource management",
    icon: Droplets,
    services: [
      {
        id: "water_permit",
        name: "Water Abstraction Permit",
        description: "Permit to abstract water from natural sources",
        duration: 60,
        fee: 25000,
        requirements: ["Environmental impact assessment", "Technical drawings", "Company registration"],
      },
      {
        id: "borehole_permit",
        name: "Borehole Drilling Permit",
        description: "Permit for borehole drilling",
        duration: 30,
        fee: 15000,
        requirements: ["Land documents", "Technical specifications", "Valid ID"],
      },
      {
        id: "irrigation_license",
        name: "Irrigation License",
        description: "License for irrigation projects",
        duration: 45,
        fee: 30000,
        requirements: ["Project proposal", "Environmental clearance", "Land documents"],
      },
    ],
  },
  {
    id: "environment",
    name: "Federal Ministry of Environment",
    description: "Environmental protection, climate change, and conservation services",
    icon: TreePine,
    services: [
      {
        id: "eia_approval",
        name: "Environmental Impact Assessment",
        description: "EIA approval for development projects",
        duration: 90,
        fee: 100000,
        requirements: ["Project proposal", "Environmental study", "Public consultation report"],
      },
      {
        id: "waste_permit",
        name: "Waste Management Permit",
        description: "Permit for waste management operations",
        duration: 60,
        fee: 50000,
        requirements: ["Waste management plan", "Technical specifications", "Company registration"],
      },
      {
        id: "forest_permit",
        name: "Forest Use Permit",
        description: "Permit for forest resource utilization",
        duration: 45,
        fee: 20000,
        requirements: ["Forest management plan", "Environmental clearance", "Valid ID"],
      },
    ],
  },
  {
    id: "industry",
    name: "Federal Ministry of Industry, Trade and Investment",
    description: "Industrial development, trade promotion, and investment facilitation",
    icon: Factory,
    services: [
      {
        id: "industrial_permit",
        name: "Industrial Development Permit",
        description: "Permit for industrial operations",
        duration: 90,
        fee: 200000,
        requirements: ["Business plan", "Environmental clearance", "Technical specifications"],
      },
      {
        id: "export_permit",
        name: "Export Permit",
        description: "Permit for export of goods",
        duration: 30,
        fee: 10000,
        requirements: ["Export documents", "Quality certificates", "Company registration"],
      },
      {
        id: "investment_certificate",
        name: "Investment Certificate",
        description: "Certificate for foreign investment",
        duration: 60,
        fee: 50000,
        requirements: ["Investment proposal", "Financial statements", "Company documents"],
      },
    ],
  },
  {
    id: "labour",
    name: "Federal Ministry of Labour and Employment",
    description: "Employment services, labor relations, and workplace safety",
    icon: Users,
    services: [
      {
        id: "work_permit",
        name: "Work Permit",
        description: "Work permit for foreign nationals",
        duration: 60,
        fee: 100000,
        requirements: ["Employment offer", "Qualifications", "Medical certificate"],
      },
      {
        id: "safety_certificate",
        name: "Workplace Safety Certificate",
        description: "Workplace safety compliance certificate",
        duration: 45,
        fee: 25000,
        requirements: ["Safety audit report", "Training records", "Company registration"],
      },
      {
        id: "employment_registration",
        name: "Employment Agency Registration",
        description: "Register employment agency",
        duration: 30,
        fee: 15000,
        requirements: ["Business plan", "Office address", "Valid ID"],
      },
    ],
  },
  {
    id: "foreign_affairs",
    name: "Federal Ministry of Foreign Affairs",
    description: "Diplomatic services, consular affairs, and international relations",
    icon: Globe,
    services: [
      {
        id: "diplomatic_passport",
        name: "Diplomatic Passport",
        description: "Passport for diplomatic personnel",
        duration: 30,
        fee: 0,
        requirements: ["Diplomatic appointment", "Official letter", "Passport photographs"],
      },
      {
        id: "consular_services",
        name: "Consular Services",
        description: "Various consular services for citizens abroad",
        duration: 45,
        fee: 20000,
        requirements: ["Valid passport", "Proof of citizenship", "Application form"],
      },
      {
        id: "treaty_certification",
        name: "Treaty Certification",
        description: "Certification of international treaties",
        duration: 60,
        fee: 50000,
        requirements: ["Treaty documents", "Legal opinion", "Official request"],
      },
    ],
  },
  {
    id: "defence",
    name: "Federal Ministry of Defence",
    description: "Defense services, military affairs, and security clearance",
    icon: Shield,
    services: [
      {
        id: "security_clearance",
        name: "Security Clearance",
        description: "Security clearance for sensitive positions",
        duration: 90,
        fee: 30000,
        requirements: ["Employment letter", "Background check", "Guarantor forms"],
      },
      {
        id: "military_pension",
        name: "Military Pension Application",
        description: "Apply for military pension benefits",
        duration: 60,
        fee: 0,
        requirements: ["Service records", "Medical certificate", "Valid ID"],
      },
      {
        id: "arms_license",
        name: "Arms License",
        description: "License for firearms possession",
        duration: 120,
        fee: 50000,
        requirements: ["Police report", "Medical certificate", "Training certificate"],
      },
    ],
  },
  {
    id: "science_technology",
    name: "Federal Ministry of Science and Technology",
    description: "Scientific research, technology development, and innovation services",
    icon: Cpu,
    services: [
      {
        id: "research_permit",
        name: "Research Permit",
        description: "Permit for scientific research activities",
        duration: 45,
        fee: 20000,
        requirements: ["Research proposal", "Institutional affiliation", "Ethical clearance"],
      },
      {
        id: "patent_application",
        name: "Patent Application",
        description: "Apply for patent protection",
        duration: 180,
        fee: 75000,
        requirements: ["Invention description", "Technical drawings", "Prior art search"],
      },
      {
        id: "technology_transfer",
        name: "Technology Transfer License",
        description: "License for technology transfer",
        duration: 90,
        fee: 100000,
        requirements: ["Technology description", "Transfer agreement", "Technical specifications"],
      },
    ],
  },
]

export const nigerianStates = [
  {
    name: "Abia",
    locations: ["Umuahia", "Aba", "Arochukwu", "Ohafia", "Bende"],
  },
  {
    name: "Adamawa",
    locations: ["Yola", "Mubi", "Numan", "Jimeta", "Ganye"],
  },
  {
    name: "Akwa Ibom",
    locations: ["Uyo", "Ikot Ekpene", "Eket", "Oron", "Abak"],
  },
  {
    name: "Anambra",
    locations: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala"],
  },
  {
    name: "Bauchi",
    locations: ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum"],
  },
  {
    name: "Bayelsa",
    locations: ["Yenagoa", "Brass", "Sagbama", "Ogbia", "Nembe"],
  },
  {
    name: "Benue",
    locations: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya"],
  },
  {
    name: "Borno",
    locations: ["Maiduguri", "Biu", "Bama", "Dikwa", "Gubio"],
  },
  {
    name: "Cross River",
    locations: ["Calabar", "Ugep", "Ogoja", "Ikom", "Obudu"],
  },
  {
    name: "Delta",
    locations: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"],
  },
  {
    name: "Ebonyi",
    locations: ["Abakaliki", "Afikpo", "Onueke", "Ezza", "Ishielu"],
  },
  {
    name: "Edo",
    locations: ["Benin City", "Auchi", "Ekpoma", "Uromi", "Igarra"],
  },
  {
    name: "Ekiti",
    locations: ["Ado-Ekiti", "Ikere", "Ilawe", "Ijero", "Emure"],
  },
  {
    name: "Enugu",
    locations: ["Enugu", "Nsukka", "Oji River", "Agbani", "Awgu"],
  },
  {
    name: "FCT",
    locations: ["Abuja", "Gwagwalada", "Kuje", "Kwali", "Bwari"],
  },
  {
    name: "Gombe",
    locations: ["Gombe", "Billiri", "Kaltungo", "Dukku", "Bajoga"],
  },
  {
    name: "Imo",
    locations: ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta"],
  },
  {
    name: "Jigawa",
    locations: ["Dutse", "Hadejia", "Kazaure", "Ringim", "Gumel"],
  },
  {
    name: "Kaduna",
    locations: ["Kaduna", "Zaria", "Kafanchan", "Sabon Gari", "Soba"],
  },
  {
    name: "Kano",
    locations: ["Kano", "Wudil", "Gwarzo", "Rano", "Karaye"],
  },
  {
    name: "Katsina",
    locations: ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma"],
  },
  {
    name: "Kebbi",
    locations: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Bagudo"],
  },
  {
    name: "Kogi",
    locations: ["Lokoja", "Okene", "Kabba", "Anyigba", "Idah"],
  },
  {
    name: "Kwara",
    locations: ["Ilorin", "Offa", "Omu-Aran", "Lafiagi", "Pategi"],
  },
  {
    name: "Lagos",
    locations: ["Ikeja", "Lagos Island", "Victoria Island", "Ikorodu", "Epe"],
  },
  {
    name: "Nasarawa",
    locations: ["Lafia", "Keffi", "Akwanga", "Nasarawa", "Doma"],
  },
  {
    name: "Niger",
    locations: ["Minna", "Bida", "Kontagora", "Suleja", "New Bussa"],
  },
  {
    name: "Ogun",
    locations: ["Abeokuta", "Sagamu", "Ijebu Ode", "Ilaro", "Ota"],
  },
  {
    name: "Ondo",
    locations: ["Akure", "Ondo", "Owo", "Ikare", "Okitipupa"],
  },
  {
    name: "Osun",
    locations: ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Iwo"],
  },
  {
    name: "Oyo",
    locations: ["Ibadan", "Ogbomoso", "Oyo", "Iseyin", "Saki"],
  },
  {
    name: "Plateau",
    locations: ["Jos", "Bukuru", "Shendam", "Pankshin", "Mangu"],
  },
  {
    name: "Rivers",
    locations: ["Port Harcourt", "Obio-Akpor", "Okrika", "Bonny", "Degema"],
  },
  {
    name: "Sokoto",
    locations: ["Sokoto", "Tambuwal", "Gwadabawa", "Bodinga", "Yabo"],
  },
  {
    name: "Taraba",
    locations: ["Jalingo", "Wukari", "Bali", "Gembu", "Serti"],
  },
  {
    name: "Yobe",
    locations: ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam"],
  },
  {
    name: "Zamfara",
    locations: ["Gusau", "Kaura Namoda", "Talata Mafara", "Zurmi", "Anka"],
  },
]
